name: Image build and push

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: trading-box/repo-xui/xui
          tag_with_ref: true

          docker run -itd --network=host \
    -v /root/x-ui/db/:/etc/x-ui/ \
    -v /root/x-ui/cert/:/root/cert/ \
    --name x-ui --restart=unless-stopped \
    enwaiax/x-ui:latest